### PR TITLE
Fix default config

### PR DESCRIPTION
**Pull request by eliecharra**
Enable docker backend by default

### CODE REVIEW

**Comment by eliecharra** [comment]
ping @jcrombez https://github.com/kibatic/ansible-traefik/pull/6 was incomplete my bad ...

**Review by jcrombez — APPROVED** [review]

**Comment by jcrombez** [comment]
The ci got a timeout, we need a restart.

**Comment by eliecharra** [comment]
F**k docker hub 

```
Error response from daemon: Get https://registry-1.docker.io/v2/kitpages/docker-ansible/manifests/2.0: dial tcp 52.55.240.129:443: i/o timeout
```

**Comment by eliecharra** [comment]
ping @jcrombez CI restarted ...

**Pull request merged**
