### PR TITLE
Install the newest traefik versions

### PR DESCRIPTION
**Pull request by Mehonoshin**
Hey folks, I found out that current ansible role is not able to install latest Traefik versions, because they are not shipped just as binaries anymore.
From now they are shipped in `tar.gz` archives, so we need to load and extract them.

I know that this PR does not cover update scenario, but please tell me if this repo is alive and it's worth to improve my PR.
We can also support both way, for example have a fallback to and old method when someone tries to install a version that is shipped as a simple binary.

### CODE REVIEW

**Review by eliecharra — CHANGES_REQUESTED** [review]
Thanks for your PR @Mehonoshin ! This repo is still alive and used :wink: 

A few things to fix before we get this merged :

- Could you update default vars and put the latest stable 2.x release URL there https://github.com/kibatic/ansible-traefik/blob/master/defaults/main.yml#L4
- We need to handle the update scenario

**Comment by Mehonoshin** [comment]
@eliecharra thanks for response!

**Comment by sklirg** [comment]
I just used these changes to upgrade my installation to v2.0 (and to v2.1). It worked fine for my setup.

I'm not sure what you mean by the "update scenario", but if there are plans of handling configuration changes using the migration tool; I think that's more effort than it's worth. Most likely, users will have to modify the configuration file manually anyways, as some of the default settings in traefik.toml need to be moved into a dynamic configuration instead of in the static (traefik.toml). Some of the big ones are automatic redirect from HTTP to HTTPS for entrypoints as well as possibly ACME/LetsEncrypt-related configurations.

If it's simply about handling whether to use unarchive or get_url, I think that can be achieved by checking if the URL ends in `tar.gz` or not :-)

I'd love to see this merged soon so I can run this role cleanly again.

**Comment by jcrombez** [comment]
Sorry for the delay but we don't use traefik 2.x internally yet and we are running very low on resources to review such major PR.

**Comment by alex-roman** [comment]
Just tested this PR on a couple of my servers. Works as expected. Please merge
`traefik_binary_url: https://github.com/traefik/traefik/releases/download/v2.3.2/traefik_v2.3.2_linux_amd64.tar.gz`

**Comment by Va1** [comment]
is this gonna be merged anytime soon?

**Comment by jcrombez** [comment]
Sorry but we decided to stop maintaining this ansible role, we don't use it anymore, i'll merge this and add a mention in the README.

**Review by jcrombez — APPROVED** [review]

**Pull request merged**
